### ISSUE TITLE
Discrepancy in Inheritance Ratio (IR) Cutoff Values Between Paper and Code

### ISSUE THREAD

**Issue by ShashankStrand** [HUGLeipzig/altafplotter#2]
Hi,

I hope this message finds you well. I have been working with your code for detecting uniparental disomy (UPD) and have come across a discrepancy that I wanted to bring to your attention.

In your paper, it is mentioned that the IR cutoff is 5 in trio analyses and 2 in duo analyses. However, upon reviewing the code, it appears that these cutoff values are reversed, with the code using an IR cutoff of 5 for duos and 2 for trios.

Could you please clarify which cutoff values are correct? This information is crucial for ensuring accurate analysis in my work.

Thank you for your attention to this matter, and I look forward to your guidance.

**Comment by maxmilianr** [comment]
Hi,
thanks for pointing this out.

I found the figure legend to be false. The cutoffs mentioned there are switched. At other points in the paper and in the code it is correct:
2 for trios
5 for duos

We will correct this for the final verison of the paper.

Best,
Max

**Comment by ShashankStrand** [comment]
Thanks for the clarification.

Regards

Shashank Kumar
